# configs/defaults/binance_settings.yaml
binance_settings:
  api_key: ""                         # Your Binance API key. Can be left empty if set via BINANCE_API_KEY env var.
  api_secret: ""                      # Your Binance API secret. Can be left empty if set via BINANCE_API_SECRET env var.
  testnet: True                       # Set to True to use Binance Testnet, False for production.
  default_symbol: "BTCUSDT"           # The default trading pair for data fetching
  historical_interval: "1h"           # Default K-line interval for historical data (e.g., '1m', '15m', '30m', '1h')
  historical_cache_dir: "data_cache/" # Directory to store cached historical data (relative to project root)

  # Default date range for training data (for train_agent.py, can be overridden by config.yaml)
  start_date_train: "2025-01-01 00:00:00" # Start datetime for training data download (YYYY-MM-DD HH:MM:SS)
  end_date_train: "2025-01-02 00:00:00"   # End datetime for training data download (YYYY-MM-DD HH:MM:SS)

  api_request_delay_seconds: 0.2      # Delay between consecutive API requests to avoid rate limits
  log_level: "normal"                 # Log level for Binance API interactions: "none", "normal", "detailed"
