# configs/defaults/binance_settings.yaml
binance_settings:
  api_key: ""                         # Your Binance API key. Can be left empty if set via BINANCE_API_KEY env var.
  api_secret: ""                      # Your Binance API secret. Can be left empty if set via BINANCE_API_SECRET env var.
  testnet: True                       # Set to True to use Binance Testnet, False for production.
  api_request_delay_seconds: 0.2      # Delay between consecutive API requests to avoid rate limits
  log_level: "normal"                 # Log level for Binance API interactions: "none", "normal", "detailed"