# configs/defaults/run_settings.yaml
run_settings:
  env_type: "simple"                  # Environment to use. Options: "simple", or any filename in src/environments/experiments/
  log_level: "normal"                 # Level of console logging: "none", "normal", "detailed"
  log_dir_base: "logs/"               # Base directory for all training logs (relative to project root)
  eval_log_dir: "logs/evaluation/"    # Base directory for evaluation run logs (relative to project root)
  model_name: "tick_trading_agent"    # Base name for saved models and log directories
  model_path: null                    # Explicit path to a .zip model file to load for evaluation/live trading (e.g., "logs/training/your_hash_model_name/best_model/best_model.zip"). If null, path is reconstructed by hash.
  alt_model_path: null                # An alternative model path, useful for comparison or secondary models.
  deterministic_prediction: True      # Use deterministic actions during evaluation and live trading
  eval_freq_episodes: 10              # Number of training episodes between evaluations (for EvalCallback)
  n_evaluation_episodes: 3            # Number of episodes to run during each evaluation callback or standalone eval
  print_step_info_freq: 50            # Print step info every X steps during evaluation (when log_level is 'normal')
  continue_from_existing_model: false # Set to true to attempt to load and continue training from a model in the same log directory
  save_on_interrupt: true             # Save model if training is KeyboardInterrupted
  save_checkpoints: true              # Enable periodic checkpoint saving during training
  num_checkpoints_to_save: 5          # Number of checkpoints to aim for (save_freq is derived from this and total_timesteps)
  use_stop_training_callback: true    # Use StopTrainingOnNoModelImprovement callback
  stop_training_patience_evals: 5     # Patience for StopTrainingOnNoModelImprovement (in number of evaluations)
  stop_training_min_evals: 10         # Minimum number of evaluations before StopTrainingOnNoModelImprovement can trigger
  device: "auto"                      # Device for training: "auto", "cpu", "cuda"

  # --- Data and Symbol Settings (Moved from binance_settings) ---
  default_symbol: "BTCUSDT"           # The default trading pair for data fetching
  historical_interval: "1h"           # Default K-line interval for historical data (e.g., '1m', '15m', '30m', '1h')
  historical_cache_dir: "data/"       # Directory to store cached historical data (relative to project root)
  
  # --- Training Period (Moved from binance_settings) ---
  start_date_train: "2025-01-01 00:00:00" # Start datetime for training data (YYYY-MM-DD HH:MM:SS)
  end_date_train: "2025-01-02 00:00:00"   # End datetime for training data (YYYY-MM-DD HH:MM:SS)

  # --- Evaluation Period (Moved from evaluation_data) ---
  start_date_eval: "2024-01-04 00:00:00" # Start datetime for evaluation period (YYYY-MM-DD HH:MM:SS)
  end_date_eval: "2024-01-04 23:59:59"   # End datetime for evaluation period (YYYY-MM-DD HH:MM:SS)