# config.yaml

agent_type: "PPO"

binance_settings: 
  testnet: false 

run_settings:
  log_level: "normal"
  continue_from_existing_model: true
  default_symbol: "BTCUSDT"
  historical_interval: "1h"
  start_date_train: "2025-01-01 00:00:00"
  end_date_train: "2025-02-01 23:59:59"
  start_date_eval: "2025-02-02 13:00:00"
  end_date_eval: "2025-02-09 23:59:59"

environment:
  kline_window_size: 3
  kline_price_features:
    - "Open"
    - "High"
    - "Low"
    - "Close"
    - "Volume" 
    - "RSI_7"   

  tick_feature_window_size: 10
  tick_features_to_use:
    - "Price"
    - "Quantity"

  tick_resample_interval_ms: 60000   

ppo_params:
  total_timesteps: 200000
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: 0.02
  policy_kwargs:
    net_arch: [64, 64]
 